export const ingredients = [
  { value: '1', label: 'Garlic' },
  { value: '2', label: 'Onion' },
  { value: '3', label: 'Chicken' },
  { value: '4', label: 'Pork' },
  { value: '5', label: 'Beef' },
  { value: '6', label: 'Carrot' },
  { value: '7', label: 'Potato' },
  { value: '8', label: 'Tomato' },
  { value: '9', label: 'Cucumber' },
  { value: '10', label: 'Broccoli' },
  { value: '11', label: 'Spinach' },
  { value: '12', label: 'Lettuce' },
  { value: '13', label: 'Bell Pepper' },
  { value: '14', label: 'Mushroom' },
  { value: '15', label: 'Zucchini' },
  { value: '16', label: 'Eggplant' },
  { value: '17', label: 'Celery' },
  { value: '18', label: 'Peas' },
  { value: '19', label: 'Corn' },
  { value: '20', label: 'Green Beans' },
  { value: '21', label: 'Cauliflower' },
  { value: '22', label: 'Cabbage' },
  { value: '23', label: 'Pumpkin' },
  { value: '24', label: 'Asparagus' },
  { value: '25', label: 'Sweet Potato' },
  { value: '26', label: 'Chili Pepper' },
  { value: '27', label: 'Ginger' },
  { value: '28', label: 'Lemon' },
  { value: '29', label: 'Lime' },
  { value: '30', label: 'Apple' },
  { value: '31', label: 'Banana' },
  { value: '32', label: 'Strawberry' },
  { value: '33', label: 'Blueberry' },
  { value: '34', label: 'Raspberry' },
  { value: '35', label: 'Peach' },
  { value: '36', label: 'Pear' },
  { value: '37', label: 'Pineapple' },
  { value: '38', label: 'Mango' },
  { value: '39', label: 'Papaya' },
  { value: '40', label: 'Watermelon' },
  { value: '41', label: 'Coconut' },
  { value: '42', label: 'Almond' },
  { value: '43', label: 'Walnut' },
  { value: '44', label: 'Cashew' },
  { value: '45', label: 'Pistachio' },
  { value: '46', label: 'Sunflower Seed' },
  { value: '47', label: 'Pumpkin Seed' },
  { value: '48', label: 'Sesame Seed' },
  { value: '49', label: 'Basil' },
  { value: '50', label: 'Oregano' }
]
