export const ingredients = [
  {
    value: '1',
    label: 'Garlic',
    unit: 'kg',
    format: 1,
    price: 10.0,
    category_id: '1',
    sub_category_id: '1',
    brand_id: 'A',
    alert_threshold: 5
  },
  {
    value: '2',
    label: 'Onion',
    unit: 'kg',
    format: 2,
    price: 12.5,
    category_id: '1',
    sub_category_id: '2',
    brand_id: 'B',
    alert_threshold: 10
  },
  {
    value: '3',
    label: 'Chicken',
    unit: 'kg',
    format: 4,
    price: 150.0,
    category_id: '2',
    sub_category_id: '1',
    brand_id: 'C',
    alert_threshold: 3
  },
  {
    value: '4',
    label: 'Pork',
    unit: 'kg',
    format: 1,
    price: 200.0,
    category_id: '2',
    sub_category_id: '2',
    brand_id: 'D',
    alert_threshold: 4
  },
  {
    value: '5',
    label: 'Beef',
    unit: 'kg',
    format: 2,
    price: 250.0,
    category_id: '2',
    sub_category_id: '3',
    brand_id: 'E',
    alert_threshold: 2
  },
  {
    value: '6',
    label: 'Carrot',
    unit: 'kg',
    format: 4,
    price: 30.0,
    category_id: '3',
    sub_category_id: '1',
    brand_id: 'F',
    alert_threshold: 15
  },
  {
    value: '7',
    label: 'Potato',
    unit: 'kg',
    format: 1,
    price: 25.0,
    category_id: '3',
    sub_category_id: '2',
    brand_id: 'G',
    alert_threshold: 10
  },
  {
    value: '8',
    label: 'Tomato',
    unit: 'kg',
    format: 2,
    price: 40.0,
    category_id: '3',
    sub_category_id: '3',
    brand_id: 'H',
    alert_threshold: 7
  },
  {
    value: '9',
    label: 'Cucumber',
    unit: 'kg',
    format: 4,
    price: 20.0,
    category_id: '3',
    sub_category_id: '4',
    brand_id: 'I',
    alert_threshold: 12
  },
  {
    value: '10',
    label: 'Broccoli',
    unit: 'kg',
    format: 1,
    price: 45.0,
    category_id: '3',
    sub_category_id: '5',
    brand_id: 'J',
    alert_threshold: 6
  },
  {
    value: '11',
    label: 'Spinach',
    unit: 'kg',
    format: 2,
    price: 35.0,
    category_id: '3',
    sub_category_id: '6',
    brand_id: 'K',
    alert_threshold: 8
  },
  {
    value: '12',
    label: 'Lettuce',
    unit: 'kg',
    format: 4,
    price: 50.0,
    category_id: '3',
    sub_category_id: '7',
    brand_id: 'L',
    alert_threshold: 3
  },
  {
    value: '13',
    label: 'Bell Pepper',
    unit: 'kg',
    format: 1,
    price: 60.0,
    category_id: '3',
    sub_category_id: '8',
    brand_id: 'M',
    alert_threshold: 5
  },
  {
    value: '14',
    label: 'Mushroom',
    unit: 'kg',
    format: 2,
    price: 75.0,
    category_id: '4',
    sub_category_id: '1',
    brand_id: 'N',
    alert_threshold: 4
  },
  {
    value: '15',
    label: 'Zucchini',
    unit: 'kg',
    format: 4,
    price: 55.0,
    category_id: '3',
    sub_category_id: '9',
    brand_id: 'O',
    alert_threshold: 2
  },
  {
    value: '16',
    label: 'Eggplant',
    unit: 'kg',
    format: 1,
    price: 40.0,
    category_id: '3',
    sub_category_id: '10',
    brand_id: 'P',
    alert_threshold: 6
  },
  {
    value: '17',
    label: 'Celery',
    unit: 'kg',
    format: 2,
    price: 20.0,
    category_id: '3',
    sub_category_id: '11',
    brand_id: 'Q',
    alert_threshold: 5
  },
  {
    value: '18',
    label: 'Peas',
    unit: 'kg',
    format: 4,
    price: 30.0,
    category_id: '3',
    sub_category_id: '12',
    brand_id: 'R',
    alert_threshold: 10
  },
  {
    value: '19',
    label: 'Corn',
    unit: 'kg',
    format: 1,
    price: 35.0,
    category_id: '3',
    sub_category_id: '13',
    brand_id: 'S',
    alert_threshold: 7
  },
  {
    value: '20',
    label: 'Green Beans',
    unit: 'kg',
    format: 2,
    price: 25.0,
    category_id: '3',
    sub_category_id: '14',
    brand_id: 'T',
    alert_threshold: 4
  },
  {
    value: '21',
    label: 'Cauliflower',
    unit: 'kg',
    format: 4,
    price: 50.0,
    category_id: '3',
    sub_category_id: '15',
    brand_id: 'U',
    alert_threshold: 8
  },
  {
    value: '22',
    label: 'Cabbage',
    unit: 'kg',
    format: 1,
    price: 15.0,
    category_id: '3',
    sub_category_id: '16',
    brand_id: 'V',
    alert_threshold: 5
  },
  {
    value: '23',
    label: 'Pumpkin',
    unit: 'kg',
    format: 2,
    price: 60.0,
    category_id: '3',
    sub_category_id: '17',
    brand_id: 'W',
    alert_threshold: 6
  },
  {
    value: '24',
    label: 'Asparagus',
    unit: 'kg',
    format: 4,
    price: 70.0,
    category_id: '3',
    sub_category_id: '18',
    brand_id: 'X',
    alert_threshold: 3
  },
  {
    value: '25',
    label: 'Sweet Potato',
    unit: 'kg',
    format: 1,
    price: 40.0,
    category_id: '3',
    sub_category_id: '19',
    brand_id: 'Y',
    alert_threshold: 4
  },
  {
    value: '26',
    label: 'Chili Pepper',
    unit: 'kg',
    format: 2,
    price: 80.0,
    category_id: '3',
    sub_category_id: '20',
    brand_id: 'Z',
    alert_threshold: 2
  },
  {
    value: '27',
    label: 'Ginger',
    unit: 'kg',
    format: 4,
    price: 45.0,
    category_id: '4',
    sub_category_id: '2',
    brand_id: 'AA',
    alert_threshold: 9
  },
  {
    value: '28',
    label: 'Lemon',
    unit: 'kg',
    format: 1,
    price: 25.0,
    category_id: '3',
    sub_category_id: '21',
    brand_id: 'AB',
    alert_threshold: 5
  },
  {
    value: '29',
    label: 'Lime',
    unit: 'kg',
    format: 2,
    price: 30.0,
    category_id: '3',
    sub_category_id: '22',
    brand_id: 'AC',
    alert_threshold: 6
  },
  {
    value: '30',
    label: 'Apple',
    unit: 'kg',
    format: 4,
    price: 50.0,
    category_id: '5',
    sub_category_id: '1',
    brand_id: 'AD',
    alert_threshold: 10
  },
  {
    value: '31',
    label: 'Banana',
    unit: 'kg',
    format: 1,
    price: 15.0,
    category_id: '5',
    sub_category_id: '2',
    brand_id: 'AE',
    alert_threshold: 7
  },
  {
    value: '32',
    label: 'Strawberry',
    unit: 'kg',
    format: 2,
    price: 100.0,
    category_id: '5',
    sub_category_id: '3',
    brand_id: 'AF',
    alert_threshold: 3
  },
  {
    value: '33',
    label: 'Blueberry',
    unit: 'kg',
    format: 4,
    price: 120.0,
    category_id: '5',
    sub_category_id: '4',
    brand_id: 'AG',
    alert_threshold: 6
  },
  {
    value: '34',
    label: 'Raspberry',
    unit: 'kg',
    format: 1,
    price: 150.0,
    category_id: '5',
    sub_category_id: '5',
    brand_id: 'AH',
    alert_threshold: 5
  },
  {
    value: '35',
    label: 'Peach',
    unit: 'kg',
    format: 2,
    price: 110.0,
    category_id: '5',
    sub_category_id: '6',
    brand_id: 'AI',
    alert_threshold: 4
  },
  {
    value: '36',
    label: 'Pear',
    unit: 'kg',
    format: 4,
    price: 130.0,
    category_id: '5',
    sub_category_id: '7',
    brand_id: 'AJ',
    alert_threshold: 2
  },
  {
    value: '37',
    label: 'Pineapple',
    unit: 'kg',
    format: 1,
    price: 60.0,
    category_id: '5',
    sub_category_id: '8',
    brand_id: 'AK',
    alert_threshold: 7
  },
  {
    value: '38',
    label: 'Mango',
    unit: 'kg',
    format: 2,
    price: 80.0,
    category_id: '5',
    sub_category_id: '9',
    brand_id: 'AL',
    alert_threshold: 6
  },
  {
    value: '39',
    label: 'Papaya',
    unit: 'kg',
    format: 4,
    price: 55.0,
    category_id: '5',
    sub_category_id: '10',
    brand_id: 'AM',
    alert_threshold: 9
  },
  {
    value: '40',
    label: 'Watermelon',
    unit: 'kg',
    format: 1,
    price: 45.0,
    category_id: '5',
    sub_category_id: '11',
    brand_id: 'AN',
    alert_threshold: 5
  },
  {
    value: '41',
    label: 'Coconut',
    unit: 'kg',
    format: 2,
    price: 70.0,
    category_id: '5',
    sub_category_id: '12',
    brand_id: 'AO',
    alert_threshold: 6
  },
  {
    value: '42',
    label: 'Almond',
    unit: 'kg',
    format: 4,
    price: 200.0,
    category_id: '6',
    sub_category_id: '1',
    brand_id: 'AP',
    alert_threshold: 3
  },
  {
    value: '43',
    label: 'Walnut',
    unit: 'kg',
    format: 1,
    price: 250.0,
    category_id: '6',
    sub_category_id: '2',
    brand_id: 'AQ',
    alert_threshold: 4
  },
  {
    value: '44',
    label: 'Cashew',
    unit: 'kg',
    format: 2,
    price: 220.0,
    category_id: '6',
    sub_category_id: '3',
    brand_id: 'AR',
    alert_threshold: 5
  },
  {
    value: '45',
    label: 'Pistachio',
    unit: 'kg',
    format: 4,
    price: 300.0,
    category_id: '6',
    sub_category_id: '4',
    brand_id: 'AS',
    alert_threshold: 6
  },
  {
    value: '46',
    label: 'Sunflower Seed',
    unit: 'kg',
    format: 1,
    price: 40.0,
    category_id: '7',
    sub_category_id: '1',
    brand_id: 'AT',
    alert_threshold: 4
  },
  {
    value: '47',
    label: 'Pumpkin Seed',
    unit: 'kg',
    format: 2,
    price: 50.0,
    category_id: '7',
    sub_category_id: '2',
    brand_id: 'AU',
    alert_threshold: 3
  },
  {
    value: '48',
    label: 'Sesame Seed',
    unit: 'kg',
    format: 4,
    price: 60.0,
    category_id: '7',
    sub_category_id: '3',
    brand_id: 'AV',
    alert_threshold: 5
  },
  {
    value: '49',
    label: 'Basil',
    unit: 'kg',
    format: 1,
    price: 20.0,
    category_id: '8',
    sub_category_id: '1',
    brand_id: 'AW',
    alert_threshold: 7
  },
  {
    value: '50',
    label: 'Oregano',
    unit: 'kg',
    format: 2,
    price: 30.0,
    category_id: '8',
    sub_category_id: '2',
    brand_id: 'AX',
    alert_threshold: 4
  }
]
